logging:
  config: ${logging.config}
  level:
    root: ${logging.level.root}
    org.hibernate.SQL: ${logging.level.org.hibernate.SQL}
    org.hibernate.type: ${logging.level.org.hibernate.type}
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create



